<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE root [
        <!ELEMENT root (station)*>
        <!ELEMENT station (id|name|lat|lon)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT lat (#PCDATA)>
        <!ELEMENT lon (#PCDATA)>
        ]>
<root>
    <station>
        <id>GM000001474</id>
        <name>BREMEN SEEFAHRTSCHULE, GM</name>
        <lat>53.1017</lat>
        <lon>8.7842</lon>
    </station>
    <station>
        <id>GM000002288</id>
        <name>KAISERSLAUTERN, GM</name>
        <lat>49.4253</lat>
        <lon>7.7367</lon>
    </station>
    <station>
        <id>GM000003038</id>
        <name>SCHWERIN, GM</name>
        <lat>53.6442</lat>
        <lon>11.3883</lon>
    </station>
    <station>
        <id>GM000003319</id>
        <name>BERLIN DAHLEM, GM</name>
        <lat>52.4639</lat>
        <lon>13.3017</lon>
    </station>
    <station>
        <id>GM000003342</id>
        <name>POTSDAM, GM</name>
        <lat>52.3833</lat>
        <lon>13.0639</lon>
    </station>
    <station>
        <id>GM000004063</id>
        <name>BAMBERG, GM</name>
        <lat>49.8753</lat>
        <lon>10.9217</lon>
    </station>
    <station>
        <id>GM000004199</id>
        <name>MUNCHEN NYMPHENBURG, GM</name>
        <lat>48.1667</lat>
        <lon>11.5025</lon>
    </station>
    <station>
        <id>GM000004204</id>
        <name>JENA STERNWARTE, GM</name>
        <lat>50.9267</lat>
        <lon>11.5842</lon>
    </station>
    <station>
        <id>GM000010147</id>
        <name>HAMBURG FUHLSBUETTEL, GM</name>
        <lat>53.635</lat>
        <lon>9.99</lon>
    </station>
    <station>
        <id>GM000010393</id>
        <name>LINDENBERG, GM</name>
        <lat>52.2094</lat>
        <lon>14.1203</lon>
    </station>
    <station>
        <id>GM000010962</id>
        <name>HOHENPEISSENBERG, GM</name>
        <lat>47.8017</lat>
        <lon>11.0117</lon>
    </station>
    <station>
        <id>GME00102177</id>
        <name>HELGOLAND, GM</name>
        <lat>54.1764</lat>
        <lon>7.8931</lon>
    </station>
    <station>
        <id>GME00102212</id>
        <name>ROSTOCK WARNEMUNDE, GM</name>
        <lat>54.1817</lat>
        <lon>12.0819</lon>
    </station>
    <station>
        <id>GME00102220</id>
        <name>GREIFSWALD, GM</name>
        <lat>54.0978</lat>
        <lon>13.4075</lon>
    </station>
    <station>
        <id>GME00102228</id>
        <name>EMDEN WOLTHUSEN, GM</name>
        <lat>53.3719</lat>
        <lon>7.2242</lon>
    </station>
    <station>
        <id>GME00102244</id>
        <name>HANNOVER, GM</name>
        <lat>52.4656</lat>
        <lon>9.6794</lon>
    </station>
    <station>
        <id>GME00102252</id>
        <name>MAGDEBURG, GM</name>
        <lat>52.1031</lat>
        <lon>11.5842</lon>
    </station>
    <station>
        <id>GME00102268</id>
        <name>DUSSELDORF, GM</name>
        <lat>51.2969</lat>
        <lon>6.77</lon>
    </station>
    <station>
        <id>GME00102284</id>
        <name>FRITZLAR, GM</name>
        <lat>51.1167</lat>
        <lon>9.2831</lon>
    </station>
    <station>
        <id>GME00102292</id>
        <name>LEIPZIG SCHKEUDITZ, GM</name>
        <lat>51.4358</lat>
        <lon>12.2414</lon>
    </station>
    <station>
        <id>GME00102324</id>
        <name>NURBURG BARWEILER, GM</name>
        <lat>50.3608</lat>
        <lon>6.8703</lon>
    </station>
    <station>
        <id>GME00102332</id>
        <name>MEININGEN, GM</name>
        <lat>50.5625</lat>
        <lon>10.3769</lon>
    </station>
    <station>
        <id>GME00102340</id>
        <name>ERFURT BINDERSLEBEN, GM</name>
        <lat>50.9844</lat>
        <lon>10.9631</lon>
    </station>
    <station>
        <id>GME00102348</id>
        <name>FICHTELBERG, GM</name>
        <lat>50.4292</lat>
        <lon>12.9553</lon>
    </station>
    <station>
        <id>GME00102356</id>
        <name>WURZBURG, GM</name>
        <lat>49.7714</lat>
        <lon>9.9589</lon>
    </station>
    <station>
        <id>GME00102364</id>
        <name>HOF, GM</name>
        <lat>50.3131</lat>
        <lon>11.8775</lon>
    </station>
    <station>
        <id>GME00102372</id>
        <name>SAARBRUCKEN ENSHEIM, GM</name>
        <lat>49.2142</lat>
        <lon>7.1081</lon>
    </station>
    <station>
        <id>GME00102380</id>
        <name>NURNBERG, GM</name>
        <lat>49.5042</lat>
        <lon>11.0567</lon>
    </station>
    <station>
        <id>GME00102388</id>
        <name>STRAUBING, GM</name>
        <lat>48.8283</lat>
        <lon>12.5603</lon>
    </station>
    <station>
        <id>GME00102396</id>
        <name>AUGSBURG, GM</name>
        <lat>48.4264</lat>
        <lon>10.9431</lon>
    </station>
    <station>
        <id>GME00102404</id>
        <name>KONSTANZ, GM</name>
        <lat>47.6781</lat>
        <lon>9.1908</lon>
    </station>
    <station>
        <id>GME00102412</id>
        <name>KEMPTEN, GM</name>
        <lat>47.7242</lat>
        <lon>10.3364</lon>
    </station>
    <station>
        <id>GME00111430</id>
        <name>MUENSTER OSNABRUECK AIRPORT, GM</name>
        <lat>52.1353</lat>
        <lon>7.7</lon>
    </station>
    <station>
        <id>GME00111445</id>
        <name>BERLIN TEMPELHOF, GM</name>
        <lat>52.4683</lat>
        <lon>13.4039</lon>
    </station>
    <station>
        <id>GME00111457</id>
        <name>ALTASTENBERG, GM</name>
        <lat>51.1903</lat>
        <lon>8.4681</lon>
    </station>
    <station>
        <id>GME00111464</id>
        <name>DRESDEN KLOTZSCHE, GM</name>
        <lat>51.1292</lat>
        <lon>13.7558</lon>
    </station>
    <station>
        <id>GME00111474</id>
        <name>TRIER PETRISBERG, GM</name>
        <lat>49.7492</lat>
        <lon>6.6592</lon>
    </station>
    <station>
        <id>GME00111503</id>
        <name>RHEINSTETTEN, GM</name>
        <lat>48.9733</lat>
        <lon>8.3308</lon>
    </station>
    <station>
        <id>GME00111512</id>
        <name>STUTTGART ECHTERDINGEN, GM</name>
        <lat>48.6892</lat>
        <lon>9.2253</lon>
    </station>
    <station>
        <id>GME00114621</id>
        <name>BROCKEN, GM</name>
        <lat>51.8</lat>
        <lon>10.62</lon>
    </station>
    <station>
        <id>GME00115771</id>
        <name>STUTTGART SCHNARRENBERG, GM</name>
        <lat>48.8292</lat>
        <lon>9.2008</lon>
    </station>
    <station>
        <id>GME00120922</id>
        <name>LEUCHTTURM ALTE WESER, GM</name>
        <lat>53.8631</lat>
        <lon>8.1275</lon>
    </station>
    <station>
        <id>GME00120934</id>
        <name>FELDBERG SCHWARZWALD, GM</name>
        <lat>47.8756</lat>
        <lon>8.0044</lon>
    </station>
    <station>
        <id>GME00120946</id>
        <name>FREUDENSTADT, GM</name>
        <lat>48.4544</lat>
        <lon>8.41</lon>
    </station>
    <station>
        <id>GME00120958</id>
        <name>AACHEN ORSBACH, GM</name>
        <lat>50.7992</lat>
        <lon>6.025</lon>
    </station>
    <station>
        <id>GME00120970</id>
        <name>GERA LEUMNITZ, GM</name>
        <lat>50.8819</lat>
        <lon>12.13</lon>
    </station>
    <station>
        <id>GME00120982</id>
        <name>GIESSEN WETTENBERG, GM</name>
        <lat>50.6008</lat>
        <lon>8.6506</lon>
    </station>
    <station>
        <id>GME00120994</id>
        <name>ANGERMUNDE, GM</name>
        <lat>53.0331</lat>
        <lon>13.9931</lon>
    </station>
    <station>
        <id>GME00121006</id>
        <name>GROSSER ARBER, GM</name>
        <lat>49.1139</lat>
        <lon>13.1353</lon>
    </station>
    <station>
        <id>GME00121030</id>
        <name>KIEL HOLTENAU, GM</name>
        <lat>54.3756</lat>
        <lon>10.1439</lon>
    </station>
    <station>
        <id>GME00121042</id>
        <name>KOLN BONN, GM</name>
        <lat>50.8658</lat>
        <lon>7.1583</lon>
    </station>
    <station>
        <id>GME00121054</id>
        <name>LAHR, GM</name>
        <lat>48.3656</lat>
        <lon>7.8289</lon>
    </station>
    <station>
        <id>GME00121066</id>
        <name>LEUCHTTURM KIEL, GM</name>
        <lat>54.5003</lat>
        <lon>10.2744</lon>
    </station>
    <station>
        <id>GME00121078</id>
        <name>BAD LIPPSPRINGE, GM</name>
        <lat>51.7867</lat>
        <lon>8.8394</lon>
    </station>
    <station>
        <id>GME00121090</id>
        <name>MARNITZ, GM</name>
        <lat>53.3242</lat>
        <lon>11.9333</lon>
    </station>
    <station>
        <id>GME00121102</id>
        <name>NORDERNEY, GM</name>
        <lat>53.7139</lat>
        <lon>7.1525</lon>
    </station>
    <station>
        <id>GME00121126</id>
        <name>OHRINGEN, GM</name>
        <lat>49.2081</lat>
        <lon>9.5183</lon>
    </station>
    <station>
        <id>GME00121138</id>
        <name>REGENSBURG, GM</name>
        <lat>49.0433</lat>
        <lon>12.1031</lon>
    </station>
    <station>
        <id>GME00121150</id>
        <name>BERLIN TEGEL, GM</name>
        <lat>52.5656</lat>
        <lon>13.3106</lon>
    </station>
    <station>
        <id>GME00121162</id>
        <name>STOTTEN, GM</name>
        <lat>48.6667</lat>
        <lon>9.8656</lon>
    </station>
    <station>
        <id>GME00121174</id>
        <name>WASSERKUPPE, GM</name>
        <lat>50.4978</lat>
        <lon>9.9439</lon>
    </station>
    <station>
        <id>GME00121186</id>
        <name>WEIDEN, GM</name>
        <lat>49.6669</lat>
        <lon>12.1856</lon>
    </station>
    <station>
        <id>GME00121210</id>
        <name>FURSTENZELL, GM</name>
        <lat>48.5458</lat>
        <lon>13.3544</lon>
    </station>
    <station>
        <id>GME00121222</id>
        <name>HAHN, GM</name>
        <lat>49.9475</lat>
        <lon>7.2644</lon>
    </station>
    <station>
        <id>GME00121246</id>
        <name>OFFENBACH WETTERPARK, GM</name>
        <lat>50.0892</lat>
        <lon>8.7864</lon>
    </station>
    <station>
        <id>GME00121258</id>
        <name>COTTBUS, GM</name>
        <lat>51.7775</lat>
        <lon>14.3183</lon>
    </station>
    <station>
        <id>GME00121270</id>
        <name>CUXHAVEN, GM</name>
        <lat>53.8731</lat>
        <lon>8.7067</lon>
    </station>
    <station>
        <id>GME00121306</id>
        <name>DOBERLUG KIRCHHAIN, GM</name>
        <lat>51.6467</lat>
        <lon>13.5767</lon>
    </station>
    <station>
        <id>GME00121354</id>
        <name>DRESDEN HOSTERWITZ, GM</name>
        <lat>51.0233</lat>
        <lon>13.8494</lon>
    </station>
    <station>
        <id>GME00121366</id>
        <name>DRESDEN STREHLEN, GM</name>
        <lat>51.0253</lat>
        <lon>13.7756</lon>
    </station>
    <station>
        <id>GME00121378</id>
        <name>DREWITZ BEI BURG, GM</name>
        <lat>52.2183</lat>
        <lon>12.165</lon>
    </station>
    <station>
        <id>GME00121402</id>
        <name>BAD DURKHEIM, GM</name>
        <lat>49.4728</lat>
        <lon>8.1939</lon>
    </station>
    <station>
        <id>GME00121510</id>
        <name>EBERSBERG HALBING, GM</name>
        <lat>48.1008</lat>
        <lon>11.9883</lon>
    </station>
    <station>
        <id>GME00121534</id>
        <name>EBRACH, GM</name>
        <lat>49.8531</lat>
        <lon>10.5003</lon>
    </station>
    <station>
        <id>GME00121582</id>
        <name>EICHSTATT LANDERSHOFEN, GM</name>
        <lat>48.8789</lat>
        <lon>11.2358</lon>
    </station>
    <station>
        <id>GME00121654</id>
        <name>ELLWANGEN RINDELBACH, GM</name>
        <lat>48.9903</lat>
        <lon>10.1317</lon>
    </station>
    <station>
        <id>GME00121666</id>
        <name>ELPERSBUTTEL, GM</name>
        <lat>54.0708</lat>
        <lon>9.0114</lon>
    </station>
    <station>
        <id>GME00121702</id>
        <name>BAD SOHL ELSTER, GM</name>
        <lat>50.2717</lat>
        <lon>12.2753</lon>
    </station>
    <station>
        <id>GME00121714</id>
        <name>ELZACH FISNACHT, GM</name>
        <lat>48.2019</lat>
        <lon>8.1094</lon>
    </station>
    <station>
        <id>GME00121750</id>
        <name>EMMENDINGEN MUNDINGEN, GM</name>
        <lat>48.1383</lat>
        <lon>7.8356</lon>
    </station>
    <station>
        <id>GME00121834</id>
        <name>ALTENSTADT, GM</name>
        <lat>47.8364</lat>
        <lon>10.8719</lon>
    </station>
    <station>
        <id>GME00121846</id>
        <name>ERFDE, GM</name>
        <lat>54.3008</lat>
        <lon>9.3169</lon>
    </station>
    <station>
        <id>GME00121882</id>
        <name>MOHRENDORF KLEINSEEBACH, GM</name>
        <lat>49.6506</lat>
        <lon>11.0083</lon>
    </station>
    <station>
        <id>GME00121930</id>
        <name>ESCHWEGE, GM</name>
        <lat>51.1844</lat>
        <lon>10.065</lon>
    </station>
    <station>
        <id>GME00121954</id>
        <name>ALTENTREPTOW, GM</name>
        <lat>53.6881</lat>
        <lon>13.2631</lon>
    </station>
    <station>
        <id>GME00121966</id>
        <name>ESLOHE, GM</name>
        <lat>51.2553</lat>
        <lon>8.1569</lon>
    </station>
    <station>
        <id>GME00121978</id>
        <name>ESSEN BREDENEY, GM</name>
        <lat>51.4056</lat>
        <lon>6.9683</lon>
    </station>
    <station>
        <id>GME00121990</id>
        <name>ALTGERINGSWALDE, GM</name>
        <lat>51.0892</lat>
        <lon>12.9342</lon>
    </station>
    <station>
        <id>GME00122002</id>
        <name>WEILERSWIST LOMMERSUM, GM</name>
        <lat>50.7131</lat>
        <lon>6.7917</lon>
    </station>
    <station>
        <id>GME00122038</id>
        <name>KR.ROTTAL INN FALKENBERG, GM</name>
        <lat>48.4842</lat>
        <lon>12.7256</lon>
    </station>
    <station>
        <id>GME00122050</id>
        <name>FASSBERG, GM</name>
        <lat>52.9192</lat>
        <lon>10.1839</lon>
    </station>
    <station>
        <id>GME00122086</id>
        <name>FICHTELBERG OBERFRANKEN HUTTST, GM</name>
        <lat>49.9817</lat>
        <lon>11.8392</lon>
    </station>
    <station>
        <id>GME00122098</id>
        <name>DUISBURG BAERL, GM</name>
        <lat>51.51</lat>
        <lon>6.7019</lon>
    </station>
    <station>
        <id>GME00122122</id>
        <name>HAMELN HASTENBECK, GM</name>
        <lat>52.0831</lat>
        <lon>9.4081</lon>
    </station>
    <station>
        <id>GME00122134</id>
        <name>WALTROP ABDINGHOF, GM</name>
        <lat>51.5981</lat>
        <lon>7.4056</lon>
    </station>
    <station>
        <id>GME00122146</id>
        <name>GEVELSBERG OBERBROKING, GM</name>
        <lat>51.3342</lat>
        <lon>7.3417</lon>
    </station>
    <station>
        <id>GME00122158</id>
        <name>LANDSHUT REITHOF, GM</name>
        <lat>48.5742</lat>
        <lon>12.2589</lon>
    </station>
    <station>
        <id>GME00122170</id>
        <name>ROCKENDORF, GM</name>
        <lat>50.6825</lat>
        <lon>11.5164</lon>
    </station>
    <station>
        <id>GME00122182</id>
        <name>MEINERZHAGEN REDLENDORF, GM</name>
        <lat>51.0908</lat>
        <lon>7.6294</lon>
    </station>
    <station>
        <id>GME00122194</id>
        <name>FLADUNGEN HEUFURT, GM</name>
        <lat>50.5058</lat>
        <lon>10.1681</lon>
    </station>
    <station>
        <id>GME00122218</id>
        <name>HELMSTEDT EMMERSTEDT, GM</name>
        <lat>52.2478</lat>
        <lon>10.9603</lon>
    </station>
    <station>
        <id>GME00122290</id>
        <name>FLOSSENBURG, GM</name>
        <lat>49.7328</lat>
        <lon>12.3506</lon>
    </station>
    <station>
        <id>GME00122326</id>
        <name>BIRX RHON, GM</name>
        <lat>50.5317</lat>
        <lon>10.0492</lon>
    </station>
    <station>
        <id>GME00122362</id>
        <name>FRANKFURT MAIN WESTEND, GM</name>
        <lat>50.1281</lat>
        <lon>8.6703</lon>
    </station>
    <station>
        <id>GME00122386</id>
        <name>FRANKFURT ODER, GM</name>
        <lat>52.3653</lat>
        <lon>14.5378</lon>
    </station>
    <station>
        <id>GME00122410</id>
        <name>ALTOMUNSTER MAISBRUNN, GM</name>
        <lat>48.4067</lat>
        <lon>11.3131</lon>
    </station>
    <station>
        <id>GME00122422</id>
        <name>HERSDORF WEISSENSEIFEN, GM</name>
        <lat>50.1517</lat>
        <lon>6.5531</lon>
    </station>
    <station>
        <id>GME00122434</id>
        <name>FREIAMT OTTOSCHWANDEN, GM</name>
        <lat>48.2028</lat>
        <lon>7.9342</lon>
    </station>
    <station>
        <id>GME00122446</id>
        <name>FREIBERG, GM</name>
        <lat>50.9281</lat>
        <lon>13.3389</lon>
    </station>
    <station>
        <id>GME00122458</id>
        <name>FREIBURG, GM</name>
        <lat>48.0242</lat>
        <lon>7.8353</lon>
    </station>
    <station>
        <id>GME00122482</id>
        <name>FREIBURG ELBE, GM</name>
        <lat>53.8292</lat>
        <lon>9.2494</lon>
    </station>
    <station>
        <id>GME00122494</id>
        <name>FREYSTADT OBERNDORF, GM</name>
        <lat>49.1792</lat>
        <lon>11.375</lon>
    </station>
    <station>
        <id>GME00122542</id>
        <name>FRIESOYTHE EDEWECHTERDAM, GM</name>
        <lat>53.0894</lat>
        <lon>7.9425</lon>
    </station>
    <station>
        <id>GME00122566</id>
        <name>ALZEY, GM</name>
        <lat>49.7281</lat>
        <lon>8.1167</lon>
    </station>
    <station>
        <id>GME00122602</id>
        <name>AMBERG UNTERAMMERSRICHT, GM</name>
        <lat>49.47</lat>
        <lon>11.8558</lon>
    </station>
    <station>
        <id>GME00122626</id>
        <name>FULDA, GM</name>
        <lat>50.5344</lat>
        <lon>9.6758</lon>
    </station>
    <station>
        <id>GME00122638</id>
        <name>GARDELEGEN, GM</name>
        <lat>52.5142</lat>
        <lon>11.3978</lon>
    </station>
    <station>
        <id>GME00122650</id>
        <name>AMERANG PFAFFING, GM</name>
        <lat>48.0206</lat>
        <lon>12.2939</lon>
    </station>
    <station>
        <id>GME00122698</id>
        <name>GEISENHEIM, GM</name>
        <lat>49.985</lat>
        <lon>7.9544</lon>
    </station>
    <station>
        <id>GME00122710</id>
        <name>GEISINGEN, GM</name>
        <lat>47.925</lat>
        <lon>8.6481</lon>
    </station>
    <station>
        <id>GME00122734</id>
        <name>GELBELSEE, GM</name>
        <lat>48.9489</lat>
        <lon>11.43</lon>
    </station>
    <station>
        <id>GME00122746</id>
        <name>GELDERN WALBECK, GM</name>
        <lat>51.4956</lat>
        <lon>6.2467</lon>
    </station>
    <station>
        <id>GME00122770</id>
        <name>OHLSBACH, GM</name>
        <lat>48.4339</lat>
        <lon>7.9933</lon>
    </station>
    <station>
        <id>GME00122782</id>
        <name>GENTHIN, GM</name>
        <lat>52.3892</lat>
        <lon>12.1633</lon>
    </station>
    <station>
        <id>GME00122806</id>
        <name>GERNSHEIM ALLMENDFELD, GM</name>
        <lat>49.7725</lat>
        <lon>8.5306</lon>
    </station>
    <station>
        <id>GME00122842</id>
        <name>GILSERBERG MOISCHEID, GM</name>
        <lat>50.9664</lat>
        <lon>9.0503</lon>
    </station>
    <station>
        <id>GME00122866</id>
        <name>GLUCKSTADT, GM</name>
        <lat>53.7983</lat>
        <lon>9.4306</lon>
    </station>
    <station>
        <id>GME00122878</id>
        <name>ANKLAM, GM</name>
        <lat>53.8431</lat>
        <lon>13.6856</lon>
    </station>
    <station>
        <id>GME00122890</id>
        <name>GOSSWEINSTEIN, GM</name>
        <lat>49.7667</lat>
        <lon>11.3075</lon>
    </station>
    <station>
        <id>GME00122902</id>
        <name>GOTTINGEN, GM</name>
        <lat>51.5017</lat>
        <lon>9.9528</lon>
    </station>
    <station>
        <id>GME00122938</id>
        <name>GRAFENBERG KASBERG, GM</name>
        <lat>49.665</lat>
        <lon>11.2253</lon>
    </station>
    <station>
        <id>GME00122962</id>
        <name>GRAINET REHBERG, GM</name>
        <lat>48.7903</lat>
        <lon>13.6306</lon>
    </station>
    <station>
        <id>GME00122974</id>
        <name>GRAMBEK, GM</name>
        <lat>53.5744</lat>
        <lon>10.6806</lon>
    </station>
    <station>
        <id>GME00123058</id>
        <name>GROSS LUSEWITZ, GM</name>
        <lat>54.0731</lat>
        <lon>12.3256</lon>
    </station>
    <station>
        <id>GME00123094</id>
        <name>FELDKIRCHEN WESTERHAM LENZMUHL, GM</name>
        <lat>47.9417</lat>
        <lon>11.9014</lon>
    </station>
    <station>
        <id>GME00123130</id>
        <name>GRUNDAU BREITENBORN, GM</name>
        <lat>50.2675</lat>
        <lon>9.1889</lon>
    </station>
    <station>
        <id>GME00123142</id>
        <name>GRUNOW, GM</name>
        <lat>53.3167</lat>
        <lon>13.9358</lon>
    </station>
    <station>
        <id>GME00123178</id>
        <name>GUTERSLOH, GM</name>
        <lat>51.8889</lat>
        <lon>8.3553</lon>
    </station>
    <station>
        <id>GME00123190</id>
        <name>ARNSTEIN MUDESHEIM, GM</name>
        <lat>49.9706</lat>
        <lon>9.9125</lon>
    </station>
    <station>
        <id>GME00123226</id>
        <name>OLSDORF, GM</name>
        <lat>49.9325</lat>
        <lon>6.3756</lon>
    </station>
    <station>
        <id>GME00123274</id>
        <name>HAMBURG NEUWIEDENTHAL, GM</name>
        <lat>53.4792</lat>
        <lon>9.8983</lon>
    </station>
    <station>
        <id>GME00123310</id>
        <name>ARTERN, GM</name>
        <lat>51.3756</lat>
        <lon>11.2931</lon>
    </station>
    <station>
        <id>GME00123370</id>
        <name>HANKENSBUTTEL, GM</name>
        <lat>52.7214</lat>
        <lon>10.6</lon>
    </station>
    <station>
        <id>GME00123382</id>
        <name>HARBURG, GM</name>
        <lat>48.7928</lat>
        <lon>10.7075</lon>
    </station>
    <station>
        <id>GME00123394</id>
        <name>ASCHAFFENBURG, GM</name>
        <lat>49.9789</lat>
        <lon>9.1125</lon>
    </station>
    <station>
        <id>GME00123418</id>
        <name>HARZGERODE, GM</name>
        <lat>51.6531</lat>
        <lon>11.1375</lon>
    </station>
    <station>
        <id>GME00123466</id>
        <name>HECHINGEN, GM</name>
        <lat>48.3758</lat>
        <lon>8.9808</lon>
    </station>
    <station>
        <id>GME00123574</id>
        <name>HEINSBERG SCHLEIDEN, GM</name>
        <lat>51.0425</lat>
        <lon>6.1044</lon>
    </station>
    <station>
        <id>GME00123586</id>
        <name>ASSLAR KLEIN ALTENSTADTEN, GM</name>
        <lat>50.5808</lat>
        <lon>8.4692</lon>
    </station>
    <station>
        <id>GME00123646</id>
        <name>HERRENBERG, GM</name>
        <lat>48.5928</lat>
        <lon>8.8553</lon>
    </station>
    <station>
        <id>GME00123694</id>
        <name>BAD HERSFELD, GM</name>
        <lat>50.8531</lat>
        <lon>9.7383</lon>
    </station>
    <station>
        <id>GME00123718</id>
        <name>HERZBERG, GM</name>
        <lat>51.6267</lat>
        <lon>10.3717</lon>
    </station>
    <station>
        <id>GME00123730</id>
        <name>ATTENKAM, GM</name>
        <lat>47.8781</lat>
        <lon>11.3656</lon>
    </station>
    <station>
        <id>GME00123778</id>
        <name>HILGENROTH, GM</name>
        <lat>50.7381</lat>
        <lon>7.6533</lon>
    </station>
    <station>
        <id>GME00123838</id>
        <name>AUE, GM</name>
        <lat>50.5917</lat>
        <lon>12.7156</lon>
    </station>
    <station>
        <id>GME00123862</id>
        <name>BERTSDORF HORNITZ, GM</name>
        <lat>50.9006</lat>
        <lon>14.7475</lon>
    </station>
    <station>
        <id>GME00123898</id>
        <name>HOFHEIM, GM</name>
        <lat>50.1364</lat>
        <lon>10.5167</lon>
    </station>
    <station>
        <id>GME00123922</id>
        <name>HOHN, GM</name>
        <lat>54.3128</lat>
        <lon>9.5392</lon>
    </station>
    <station>
        <id>GME00123934</id>
        <name>HOHWACHT, GM</name>
        <lat>54.3206</lat>
        <lon>10.6742</lon>
    </station>
    <station>
        <id>GME00123946</id>
        <name>HOLZDORF FLUGPLATZ, GM</name>
        <lat>51.7683</lat>
        <lon>13.1681</lon>
    </station>
    <station>
        <id>GME00123970</id>
        <name>HOLZKIRCHEN, GM</name>
        <lat>47.8831</lat>
        <lon>11.6975</lon>
    </station>
    <station>
        <id>GME00123994</id>
        <name>KR. HOLZMINDEN BEVERN, GM</name>
        <lat>51.8553</lat>
        <lon>9.4975</lon>
    </station>
    <station>
        <id>GME00124030</id>
        <name>HOMBURG SAAR, GM</name>
        <lat>49.3292</lat>
        <lon>7.3567</lon>
    </station>
    <station>
        <id>GME00124102</id>
        <name>HUMMERICH, GM</name>
        <lat>50.5664</lat>
        <lon>7.4844</lon>
    </station>
    <station>
        <id>GME00124126</id>
        <name>IDAR OBERSTEIN, GM</name>
        <lat>49.7</lat>
        <lon>7.3331</lon>
    </station>
    <station>
        <id>GME00124138</id>
        <name>IHRINGEN, GM</name>
        <lat>48.0428</lat>
        <lon>7.6328</lon>
    </station>
    <station>
        <id>GME00124186</id>
        <name>INGOLSTADT FLUGPLATZ, GM</name>
        <lat>48.7156</lat>
        <lon>11.5333</lon>
    </station>
    <station>
        <id>GME00124222</id>
        <name>ITZEHOE, GM</name>
        <lat>53.9894</lat>
        <lon>9.5694</lon>
    </station>
    <station>
        <id>GME00124234</id>
        <name>SCHLESWIG JAGEL, GM</name>
        <lat>54.4567</lat>
        <lon>9.5206</lon>
    </station>
    <station>
        <id>GME00124306</id>
        <name>JUTERBOG, GM</name>
        <lat>52.0017</lat>
        <lon>13.1039</lon>
    </station>
    <station>
        <id>GME00124318</id>
        <name>KAHL MAIN, GM</name>
        <lat>50.0656</lat>
        <lon>8.9942</lon>
    </station>
    <station>
        <id>GME00124330</id>
        <name>KAISERSBACH CRONHUTTE, GM</name>
        <lat>48.9181</lat>
        <lon>9.6881</lon>
    </station>
    <station>
        <id>GME00124366</id>
        <name>KALL SISTIG, GM</name>
        <lat>50.5028</lat>
        <lon>6.5267</lon>
    </station>
    <station>
        <id>GME00124450</id>
        <name>KEHL ODELSHOFEN, GM</name>
        <lat>48.5583</lat>
        <lon>7.8808</lon>
    </station>
    <station>
        <id>GME00124474</id>
        <name>KIRCHBERG JAGST HERBOLDSHAUSEN, GM</name>
        <lat>49.1814</lat>
        <lon>9.9808</lon>
    </station>
    <station>
        <id>GME00124486</id>
        <name>KIRCHDORF POEL, GM</name>
        <lat>54.0008</lat>
        <lon>11.4358</lon>
    </station>
    <station>
        <id>GME00124498</id>
        <name>BADEN BADEN GEROLDSAU, GM</name>
        <lat>48.7278</lat>
        <lon>8.2467</lon>
    </station>
    <station>
        <id>GME00124510</id>
        <name>BAD KISSINGEN, GM</name>
        <lat>50.2256</lat>
        <lon>10.0803</lon>
    </station>
    <station>
        <id>GME00124522</id>
        <name>MULLHEIM, GM</name>
        <lat>47.8069</lat>
        <lon>7.6392</lon>
    </station>
    <station>
        <id>GME00124534</id>
        <name>KITZINGEN, GM</name>
        <lat>49.7369</lat>
        <lon>10.1792</lon>
    </station>
    <station>
        <id>GME00124546</id>
        <name>KLEINER FELDBERG TAUNUS, GM</name>
        <lat>50.2225</lat>
        <lon>8.4481</lon>
    </station>
    <station>
        <id>GME00124570</id>
        <name>KLEINER INSELSBERG, GM</name>
        <lat>50.8469</lat>
        <lon>10.4814</lon>
    </station>
    <station>
        <id>GME00124594</id>
        <name>KLETTWITZ, GM</name>
        <lat>51.5567</lat>
        <lon>13.8864</lon>
    </station>
    <station>
        <id>GME00124606</id>
        <name>KLEVE, GM</name>
        <lat>51.7625</lat>
        <lon>6.0956</lon>
    </station>
    <station>
        <id>GME00124630</id>
        <name>KLITZSCHEN BEI TORGAU, GM</name>
        <lat>51.5203</lat>
        <lon>12.9078</lon>
    </station>
    <station>
        <id>GME00124678</id>
        <name>BAD KONIGSHOFEN, GM</name>
        <lat>50.2853</lat>
        <lon>10.4467</lon>
    </station>
    <station>
        <id>GME00124690</id>
        <name>KONIGSMOOR, GM</name>
        <lat>53.2292</lat>
        <lon>9.6533</lon>
    </station>
    <station>
        <id>GME00124726</id>
        <name>KOSCHING, GM</name>
        <lat>48.8308</lat>
        <lon>11.4883</lon>
    </station>
    <station>
        <id>GME00124762</id>
        <name>KOTHEN ANHALT, GM</name>
        <lat>51.7528</lat>
        <lon>12.0092</lon>
    </station>
    <station>
        <id>GME00124774</id>
        <name>BAD KOHLGRUB ROSSHOF, GM</name>
        <lat>47.6658</lat>
        <lon>11.0817</lon>
    </station>
    <station>
        <id>GME00124810</id>
        <name>KRONACH, GM</name>
        <lat>50.2533</lat>
        <lon>11.3219</lon>
    </station>
    <station>
        <id>GME00124846</id>
        <name>KUMMERSBRUCK, GM</name>
        <lat>49.4289</lat>
        <lon>11.9019</lon>
    </station>
    <station>
        <id>GME00124918</id>
        <name>LAAGE FLUGPLATZ, GM</name>
        <lat>53.9167</lat>
        <lon>12.2831</lon>
    </station>
    <station>
        <id>GME00124930</id>
        <name>MERKLINGEN, GM</name>
        <lat>48.5131</lat>
        <lon>9.7656</lon>
    </station>
    <station>
        <id>GME00125026</id>
        <name>LANGENLIPSDORF, GM</name>
        <lat>51.9183</lat>
        <lon>13.0889</lon>
    </station>
    <station>
        <id>GME00125074</id>
        <name>BAD LAUCHSTADT, GM</name>
        <lat>51.3925</lat>
        <lon>11.88</lon>
    </station>
    <station>
        <id>GME00125098</id>
        <name>LAUPHEIM, GM</name>
        <lat>48.2181</lat>
        <lon>9.9094</lon>
    </station>
    <station>