<!DOCTYPE stations [
        <!ELEMENT stations (station)*>
        <!ELEMENT station (name|lat|lon|data)*>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT lat (#PCDATA)>
        <!ELEMENT lon (#PCDATA)>
        <!ELEMENT data (set)*>
        <!ELEMENT set (temp|year)*>
        <!ELEMENT temp (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        ]>
<stations>
    <station>
        <name>ASN00084027</name>
        <lat>44.123</lat>
        <lon>8.43</lon>
        <data>
            <set>
                <temp>14</temp>
                <year>1945</year>
            </set>
            <set>
                <temp>34</temp>
                <year>1946</year>
            </set>
            <set>
                <temp>32</temp>
                <year>1947</year>
            </set>
        </data>
    </station>
    <station>
        <name>ASN0008345</name>
        <lat>49.02716</lat>
        <lon>8.38568</lon>
        <data>
            <set>
                <temp>-69</temp>
                <year>0</year>
            </set>
            <set>
                <temp>21</temp>
                <year>1945</year>
            </set>
            <set>
                <temp>32</temp>
                <year>1946</year>
            </set>
            <set>
                <temp>1000</temp>
                <year>1947</year>
            </set>
            <set>
                <temp>187</temp>
                <year>69420</year>
            </set>
        </data>
    </station>
</stations>