<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE root [
        <!ELEMENT root (station)*>
        <!ELEMENT station (id|name|lat|lon)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT lat (#PCDATA)>
        <!ELEMENT lon (#PCDATA)>
        ]>
<root>
    <station>
        <id>GM000001474</id>
        <name>BREMEN SEEFAHRTSCHULE, GM</name>
        <lat>53.1017</lat>
        <lon>8.7842</lon>
    </station>
    <station>
        <id>GM000002288</id>
        <name>KAISERSLAUTERN, GM</name>
        <lat>49.4253</lat>
        <lon>7.7367</lon>
    </station>
    <station>
        <id>GM000002698</id>
        <name>KARLSRUHE, GM</name>
        <lat>49.0392</lat>
        <lon>8.365</lon>
    </station>
    <station>
        <id>GM000003038</id>
        <name>SCHWERIN, GM</name>
        <lat>53.6442</lat>
        <lon>11.3883</lon>
    </station>
    <station>
        <id>GM000003218</id>
        <name>HALLE, GM</name>
        <lat>51.5144</lat>
        <lon>11.9506</lon>
    </station>
    <station>
        <id>GM000003319</id>
        <name>BERLIN DAHLEM, GM</name>
        <lat>52.4639</lat>
        <lon>13.3017</lon>
    </station>
    <station>
        <id>GM000003342</id>
        <name>POTSDAM, GM</name>
        <lat>52.3833</lat>
        <lon>13.0639</lon>
    </station>
    <station>
        <id>GM000004063</id>
        <name>BAMBERG, GM</name>
        <lat>49.8753</lat>
        <lon>10.9217</lon>
    </station>
    <station>
        <id>GM000004199</id>
        <name>MUNCHEN NYMPHENBURG, GM</name>
        <lat>48.1667</lat>
        <lon>11.5025</lon>
    </station>
    <station>
        <id>GM000004204</id>
        <name>JENA STERNWARTE, GM</name>
        <lat>50.9267</lat>
        <lon>11.5842</lon>
    </station>
    <station>
        <id>GM000010147</id>
        <name>HAMBURG FUHLSBUETTEL, GM</name>
        <lat>53.635</lat>
        <lon>9.99</lon>
    </station>
    <station>
        <id>GM000010393</id>
        <name>LINDENBERG, GM</name>
        <lat>52.2094</lat>
        <lon>14.1203</lon>
    </station>
    <station>
        <id>GM000010962</id>
        <name>HOHENPEISSENBERG, GM</name>
        <lat>47.8017</lat>
        <lon>11.0117</lon>
    </station>
    <station>
        <id>GME00102169</id>
        <name>UFS TW EMS, GM</name>
        <lat>54.1667</lat>
        <lon>6.35</lon>
    </station>
    <station>
        <id>GME00102177</id>
        <name>HELGOLAND, GM</name>
        <lat>54.1764</lat>
        <lon>7.8931</lon>
    </station>
    <station>
        <id>GME00102212</id>
        <name>ROSTOCK WARNEMUNDE, GM</name>
        <lat>54.1817</lat>
        <lon>12.0819</lon>
    </station>
    <station>
        <id>GME00102220</id>
        <name>GREIFSWALD, GM</name>
        <lat>54.0978</lat>
        <lon>13.4075</lon>
    </station>
    <station>
        <id>GME00102228</id>
        <name>EMDEN WOLTHUSEN, GM</name>
        <lat>53.3719</lat>
        <lon>7.2242</lon>
    </station>
    <station>
        <id>GME00102236</id>
        <name>NEURUPPIN, GM</name>
        <lat>52.9053</lat>
        <lon>12.8083</lon>
    </station>
    <station>
        <id>GME00102244</id>
        <name>HANNOVER, GM</name>
        <lat>52.4656</lat>
        <lon>9.6794</lon>
    </station>
    <station>
        <id>GME00102252</id>
        <name>MAGDEBURG, GM</name>
        <lat>52.1031</lat>
        <lon>11.5842</lon>
    </station>
    <station>
        <id>GME00102268</id>
        <name>DUSSELDORF, GM</name>
        <lat>51.2969</lat>
        <lon>6.77</lon>
    </station>
    <station>
        <id>GME00102276</id>
        <name>KASSEL, GM</name>
        <lat>51.2978</lat>
        <lon>9.4433</lon>
    </station>
    <station>
        <id>GME00102292</id>
        <name>LEIPZIG SCHKEUDITZ, GM</name>
        <lat>51.4358</lat>
        <lon>12.2414</lon>
    </station>
    <station>
        <id>GME00102316</id>
        <name>AACHEN, GM</name>
        <lat>50.7839</lat>
        <lon>6.095</lon>
    </station>
    <station>
        <id>GME00102324</id>
        <name>NURBURG BARWEILER, GM</name>
        <lat>50.3608</lat>
        <lon>6.8703</lon>
    </station>
    <station>
        <id>GME00102332</id>
        <name>MEININGEN, GM</name>
        <lat>50.5625</lat>
        <lon>10.3769</lon>
    </station>
    <station>
        <id>GME00102340</id>
        <name>ERFURT BINDERSLEBEN, GM</name>
        <lat>50.9844</lat>
        <lon>10.9631</lon>
    </station>
    <station>
        <id>GME00102348</id>
        <name>FICHTELBERG, GM</name>
        <lat>50.4292</lat>
        <lon>12.9553</lon>
    </station>
    <station>
        <id>GME00102356</id>
        <name>WURZBURG, GM</name>
        <lat>49.7714</lat>
        <lon>9.9589</lon>
    </station>
    <station>
        <id>GME00102364</id>
        <name>HOF, GM</name>
        <lat>50.3131</lat>
        <lon>11.8775</lon>
    </station>
    <station>
        <id>GME00102372</id>
        <name>SAARBRUCKEN ENSHEIM, GM</name>
        <lat>49.2142</lat>
        <lon>7.1081</lon>
    </station>
    <station>
        <id>GME00102380</id>
        <name>NURNBERG, GM</name>
        <lat>49.5042</lat>
        <lon>11.0567</lon>
    </station>
    <station>
        <id>GME00102388</id>
        <name>STRAUBING, GM</name>
        <lat>48.8283</lat>
        <lon>12.5603</lon>
    </station>
    <station>
        <id>GME00102396</id>
        <name>AUGSBURG, GM</name>
        <lat>48.4264</lat>
        <lon>10.9431</lon>
    </station>
    <station>
        <id>GME00102404</id>
        <name>KONSTANZ, GM</name>
        <lat>47.6781</lat>
        <lon>9.1908</lon>
    </station>
    <station>
        <id>GME00102412</id>
        <name>KEMPTEN, GM</name>
        <lat>47.7242</lat>
        <lon>10.3364</lon>
    </station>
    <station>
        <id>GME00111430</id>
        <name>MUENSTER OSNABRUECK AIRPORT, GM</name>
        <lat>52.1353</lat>
        <lon>7.7</lon>
    </station>
    <station>
        <id>GME00111445</id>
        <name>BERLIN TEMPELHOF, GM</name>
        <lat>52.4683</lat>
        <lon>13.4039</lon>
    </station>
    <station>
        <id>GME00111457</id>
        <name>ALTASTENBERG, GM</name>
        <lat>51.1903</lat>
        <lon>8.4681</lon>
    </station>
    <station>
        <id>GME00111474</id>
        <name>TRIER PETRISBERG, GM</name>
        <lat>49.7492</lat>
        <lon>6.6592</lon>
    </station>
    <station>
        <id>GME00111503</id>
        <name>RHEINSTETTEN, GM</name>
        <lat>48.9733</lat>
        <lon>8.3308</lon>
    </station>
    <station>
        <id>GME00111512</id>
        <name>STUTTGART ECHTERDINGEN, GM</name>
        <lat>48.6892</lat>
        <lon>9.2253</lon>
    </station>
    <station>
        <id>GME00114621</id>
        <name>BROCKEN, GM</name>
        <lat>51.8</lat>
        <lon>10.62</lon>
    </station>
    <station>
        <id>GME00115771</id>
        <name>STUTTGART SCHNARRENBERG, GM</name>
        <lat>48.8292</lat>
        <lon>9.2008</lon>
    </station>
    <station>
        <id>GME00120922</id>
        <name>LEUCHTTURM ALTE WESER, GM</name>
        <lat>53.8631</lat>
        <lon>8.1275</lon>
    </station>
    <station>
        <id>GME00120934</id>
        <name>FELDBERG SCHWARZWALD, GM</name>
        <lat>47.8756</lat>
        <lon>8.0044</lon>
    </station>
    <station>
        <id>GME00120946</id>
        <name>FREUDENSTADT, GM</name>
        <lat>48.4544</lat>
        <lon>8.41</lon>
    </station>
    <station>
        <id>GME00120958</id>
        <name>AACHEN ORSBACH, GM</name>
        <lat>50.7992</lat>
        <lon>6.025</lon>
    </station>
    <station>
        <id>GME00120970</id>
        <name>GERA LEUMNITZ, GM</name>
        <lat>50.8819</lat>
        <lon>12.13</lon>
    </station>
    <station>
        <id>GME00120982</id>
        <name>GIESSEN WETTENBERG, GM</name>
        <lat>50.6008</lat>
        <lon>8.6506</lon>
    </station>
    <station>
        <id>GME00120994</id>
        <name>ANGERMUNDE, GM</name>
        <lat>53.0331</lat>
        <lon>13.9931</lon>
    </station>
    <station>
        <id>GME00121006</id>
        <name>GROSSER ARBER, GM</name>
        <lat>49.1139</lat>
        <lon>13.1353</lon>
    </station>
    <station>
        <id>GME00121030</id>
        <name>KIEL HOLTENAU, GM</name>
        <lat>54.3756</lat>
        <lon>10.1439</lon>
    </station>
    <station>
        <id>GME00121042</id>
        <name>KOLN BONN, GM</name>
        <lat>50.8658</lat>
        <lon>7.1583</lon>
    </station>
    <station>
        <id>GME00121054</id>
        <name>LAHR, GM</name>
        <lat>48.3656</lat>
        <lon>7.8289</lon>
    </station>
    <station>
        <id>GME00121066</id>
        <name>LEUCHTTURM KIEL, GM</name>
        <lat>54.5003</lat>
        <lon>10.2744</lon>
    </station>
    <station>
        <id>GME00121078</id>
        <name>BAD LIPPSPRINGE, GM</name>
        <lat>51.7867</lat>
        <lon>8.8394</lon>
    </station>
    <station>
        <id>GME00121090</id>
        <name>MARNITZ, GM</name>
        <lat>53.3242</lat>
        <lon>11.9333</lon>
    </station>
    <station>
        <id>GME00121102</id>
        <name>NORDERNEY, GM</name>
        <lat>53.7139</lat>
        <lon>7.1525</lon>
    </station>
    <station>
        <id>GME00121126</id>
        <name>OHRINGEN, GM</name>
        <lat>49.2081</lat>
        <lon>9.5183</lon>
    </station>
    <station>
        <id>GME00121138</id>
        <name>REGENSBURG, GM</name>
        <lat>49.0433</lat>
        <lon>12.1031</lon>
    </station>
    <station>
        <id>GME00121150</id>
        <name>BERLIN TEGEL, GM</name>
        <lat>52.5656</lat>
        <lon>13.3106</lon>
    </station>
    <station>
        <id>GME00121162</id>
        <name>STOTTEN, GM</name>
        <lat>48.6667</lat>
        <lon>9.8656</lon>
    </station>
    <station>
        <id>GME00121174</id>
        <name>WASSERKUPPE, GM</name>
        <lat>50.4978</lat>
        <lon>9.9439</lon>
    </station>
    <station>
        <id>GME00121186</id>
        <name>WEIDEN, GM</name>
        <lat>49.6669</lat>
        <lon>12.1856</lon>
    </station>
    <station>
        <id>GME00121198</id>
        <name>WENDELSTEIN, GM</name>
        <lat>47.7042</lat>
        <lon>12.0131</lon>
    </station>
    <station>
        <id>GME00121210</id>
        <name>FURSTENZELL, GM</name>
        <lat>48.5458</lat>
        <lon>13.3544</lon>
    </station>
    <station>
        <id>GME00121222</id>
        <name>HAHN, GM</name>
        <lat>49.9475</lat>
        <lon>7.2644</lon>
    </station>
    <station>
        <id>GME00121246</id>
        <name>OFFENBACH WETTERPARK, GM</name>
        <lat>50.0892</lat>
        <lon>8.7864</lon>
    </station>
    <station>
        <id>GME00121258</id>
        <name>COTTBUS, GM</name>
        <lat>51.7775</lat>
        <lon>14.3183</lon>
    </station>
    <station>
        <id>GME00121270</id>
        <name>CUXHAVEN, GM</name>
        <lat>53.8731</lat>
        <lon>8.7067</lon>
    </station>
    <station>
        <id>GME00121282</id>
        <name>UFS DEUTSCHE BUCHT, GM</name>
        <lat>54.1667</lat>
        <lon>7.45</lon>
    </station>
    <station>
        <id>GME00121306</id>
        <name>DOBERLUG KIRCHHAIN, GM</name>
        <lat>51.6467</lat>
        <lon>13.5767</lon>
    </station>
    <station>
        <id>GME00121330</id>
        <name>DONAUESCHINGEN, GM</name>
        <lat>47.9431</lat>
        <lon>8.5056</lon>
    </station>
    <station>
        <id>GME00121354</id>
        <name>DRESDEN HOSTERWITZ, GM</name>
        <lat>51.0233</lat>
        <lon>13.8494</lon>
    </station>
    <station>
        <id>GME00121366</id>
        <name>DRESDEN STREHLEN, GM</name>
        <lat>51.0253</lat>
        <lon>13.7756</lon>
    </station>
    <station>
        <id>GME00121378</id>
        <name>DREWITZ BEI BURG, GM</name>
        <lat>52.2183</lat>
        <lon>12.165</lon>
    </station>
    <station>
        <id>GME00121402</id>
        <name>BAD DURKHEIM, GM</name>
        <lat>49.4728</lat>
        <lon>8.1939</lon>
    </station>
    <station>
        <id>GME00121450</id>
        <name>DUISBURG FRIEMERSHEIM, GM</name>
        <lat>51.3953</lat>
        <lon>6.7031</lon>
    </station>
    <station>
        <id>GME00121474</id>
        <name>EBELEBEN, GM</name>
        <lat>51.2817</lat>
        <lon>10.7375</lon>
    </station>
    <station>
        <id>GME00121486</id>
        <name>EBERBACH NECKAR, GM</name>
        <lat>49.4558</lat>
        <lon>8.9792</lon>
    </station>
    <station>
        <id>GME00121498</id>
        <name>EBERSBACH FILS, GM</name>
        <lat>48.7208</lat>
        <lon>9.5339</lon>
    </station>
    <station>
        <id>GME00121510</id>
        <name>EBERSBERG HALBING, GM</name>
        <lat>48.1008</lat>
        <lon>11.9883</lon>
    </station>
    <station>
        <id>GME00121534</id>
        <name>EBRACH, GM</name>
        <lat>49.8531</lat>
        <lon>10.5003</lon>
    </station>
    <station>
        <id>GME00121582</id>
        <name>EICHSTATT LANDERSHOFEN, GM</name>
        <lat>48.8789</lat>
        <lon>11.2358</lon>
    </station>
    <station>
        <id>GME00121654</id>
        <name>ELLWANGEN RINDELBACH, GM</name>
        <lat>48.9903</lat>
        <lon>10.1317</lon>
    </station>
    <station>
        <id>GME00121666</id>
        <name>ELPERSBUTTEL, GM</name>
        <lat>54.0708</lat>
        <lon>9.0114</lon>
    </station>
    <station>
        <id>GME00121678</id>
        <name>ELSDORF ERFTKREIS, GM</name>
        <lat>50.9292</lat>
        <lon>6.5653</lon>
    </station>
    <station>
        <id>GME00121702</id>
        <name>BAD SOHL ELSTER, GM</name>
        <lat>50.2717</lat>
        <lon>12.2753</lon>
    </station>
    <station>
        <id>GME00121714</id>
        <name>ELZACH FISNACHT, GM</name>
        <lat>48.2019</lat>
        <lon>8.1094</lon>
    </station>
    <station>
        <id>GME00121750</id>
        <name>EMMENDINGEN MUNDINGEN, GM</name>
        <lat>48.1383</lat>
        <lon>7.8356</lon>
    </station>
    <station>
        <id>GME00121786</id>
        <name>ENGEN HEGAU, GM</name>
        <lat>47.8525</lat>
        <lon>8.7681</lon>
    </station>
    <station>
        <id>GME00121810</id>
        <name>EPPINGEN, GM</name>
        <lat>49.1317</lat>
        <lon>8.9175</lon>
    </station>
    <station>
        <id>GME00121822</id>
        <name>EPPINGEN ELSENZ, GM</name>
        <lat>49.1675</lat>
        <lon>8.8531</lon>
    </station>
    <station>
        <id>GME00121846</id>
        <name>ERFDE, GM</name>
        <lat>54.3008</lat>
        <lon>9.3169</lon>
    </station>
    <station>
        <id>GME00121870</id>
        <name>ERISKIRCH MARIABRUNN, GM</name>
        <lat>47.6367</lat>
        <lon>9.5403</lon>
    </station>
    <station>
        <id>GME00121882</id>
        <name>MOHRENDORF KLEINSEEBACH, GM</name>
        <lat>49.6506</lat>
        <lon>11.0083</lon>
    </station>
    <station>
        <id>GME00121906</id>
        <name>ESCHAU HOBBACH, GM</name>
        <lat>49.86</lat>
        <lon>9.2869</lon>
    </station>
    <station>
        <id>GME00121918</id>
        <name>ESCHENBACH OBERPFALZ, GM</name>
        <lat>49.7531</lat>
        <lon>11.8233</lon>
    </station>
    <station>
        <id>GME00121930</id>
        <name>ESCHWEGE, GM</name>
        <lat>51.1844</lat>
        <lon>10.065</lon>
    </station>
    <station>
        <id>GME00121954</id>
        <name>ALTENTREPTOW, GM</name>
        <lat>53.6881</lat>
        <lon>13.2631</lon>
    </station>
    <station>
        <id>GME00121966</id>
        <name>ESLOHE, GM</name>
        <lat>51.2553</lat>
        <lon>8.1569</lon>
    </station>
    <station>
        <id>GME00121978</id>
        <name>ESSEN BREDENEY, GM</name>
        <lat>51.4056</lat>
        <lon>6.9683</lon>
    </station>
    <station>
        <id>GME00121990</id>
        <name>ALTGERINGSWALDE, GM</name>
        <lat>51.0892</lat>
        <lon>12.9342</lon>
    </station>
    <station>
        <id>GME00122002</id>
        <name>WEILERSWIST LOMMERSUM, GM</name>
        <lat>50.7131</lat>
        <lon>6.7917</lon>
    </station>
    <station>
        <id>GME00122014</id>
        <name>EUTIN, GM</name>
        <lat>54.1356</lat>
        <lon>10.5878</lon>
    </station>
    <station>
        <id>GME00122038</id>
        <name>KR.ROTTAL INN FALKENBERG, GM</name>
        <lat>48.4842</lat>
        <lon>12.7256</lon>
    </station>
    <station>
        <id>GME00122086</id>
        <name>FICHTELBERG OBERFRANKEN HUTTST, GM</name>
        <lat>49.9817</lat>
        <lon>11.8392</lon>
    </station>
    <station>
        <id>GME00122098</id>
        <name>DUISBURG BAERL, GM</name>
        <lat>51.51</lat>
        <lon>6.7019</lon>
    </station>
    <station>
        <id>GME00122122</id>
        <name>HAMELN HASTENBECK, GM</name>
        <lat>52.0831</lat>
        <lon>9.4081</lon>
    </station>
    <station>
        <id>GME00122134</id>
        <name>WALTROP ABDINGHOF, GM</name>
        <lat>51.5981</lat>
        <lon>7.4056</lon>
    </station>
    <station>
        <id>GME00122146</id>
        <name>GEVELSBERG OBERBROKING, GM</name>
        <lat>51.3342</lat>
        <lon>7.3417</lon>
    </station>
    <station>
        <id>GME00122158</id>
        <name>LANDSHUT REITHOF, GM</name>
        <lat>48.5742</lat>
        <lon>12.2589</lon>
    </station>
    <station>
        <id>GME00122170</id>
        <name>ROCKENDORF, GM</name>
        <lat>50.6825</lat>
        <lon>11.5164</lon>
    </station>
    <station>
        <id>GME00122182</id>
        <name>MEINERZHAGEN REDLENDORF, GM</name>
        <lat>51.0908</lat>
        <lon>7.6294</lon>
    </station>
    <station>
        <id>GME00122194</id>
        <name>FLADUNGEN HEUFURT, GM</name>
        <lat>50.5058</lat>
        <lon>10.1681</lon>
    </station>
    <station>
        <id>GME00122206</id>
        <name>HILDESHEIM DRISPENSTEDT, GM</name>
        <lat>52.1803</lat>
        <lon>9.9533</lon>
    </station>
    <station>
        <id>GME00122218</id>
        <name>HELMSTEDT EMMERSTEDT, GM</name>
        <lat>52.2478</lat>
        <lon>10.9603</lon>
    </station>
    <station>
        <id>GME00122290</id>
        <name>FLOSSENBURG, GM</name>
        <lat>49.7328</lat>
        <lon>12.3506</lon>
    </station>
    <station>
        <id>GME00122302</id>
        <name>FRAMMERSBACH, GM</name>
        <lat>50.0628</lat>
        <lon>9.4558</lon>
    </station>
    <station>
        <id>GME00122326</id>
        <name>BIRX RHON, GM</name>
        <lat>50.5317</lat>
        <lon>10.0492</lon>
    </station>
    <station>
        <id>GME00122362</id>
        <name>FRANKFURT MAIN WESTEND, GM</name>
        <lat>50.1281</lat>
        <lon>8.6703</lon>
    </station>
    <station>
        <id>GME00122386</id>
        <name>FRANKFURT ODER, GM</name>
        <lat>52.3653</lat>
        <lon>14.5378</lon>
    </station>
    <station>
        <id>GME00122410</id>
        <name>ALTOMUNSTER MAISBRUNN, GM</name>
        <lat>48.4067</lat>
        <lon>11.3131</lon>
    </station>
    <station>
        <id>GME00122422</id>
        <name>HERSDORF WEISSENSEIFEN, GM</name>
        <lat>50.1517</lat>
        <lon>6.5531</lon>
    </station>
    <station>
        <id>GME00122434</id>
        <name>FREIAMT OTTOSCHWANDEN, GM</name>
        <lat>48.2028</lat>
        <lon>7.9342</lon>
    </station>
    <station>
        <id>GME00122446</id>
        <name>FREIBERG, GM</name>
        <lat>50.9281</lat>
        <lon>13.3389</lon>
    </station>
    <station>
        <id>GME00122458</id>
        <name>FREIBURG, GM</name>
        <lat>48.0242</lat>
        <lon>7.8353</lon>
    </station>
    <station>
        <id>GME00122482</id>
        <name>FREIBURG ELBE, GM</name>
        <lat>53.8292</lat>
        <lon>9.2494</lon>
    </station>
    <station>
        <id>GME00122494</id>
        <name>FREYSTADT OBERNDORF, GM</name>
        <lat>49.1792</lat>
        <lon>11.375</lon>
    </station>
    <station>
        <id>GME00122530</id>
        <name>MALSBURG MARZELL FRIEDRICHSHEI, GM</name>
        <lat>47.7828</lat>
        <lon>7.7356</lon>
    </station>
    <station>
        <id>GME00122542</id>
        <name>FRIESOYTHE EDEWECHTERDAM, GM</name>
        <lat>53.0894</lat>
        <lon>7.9425</lon>
    </station>
    <station>
        <id>GME00122566</id>
        <name>ALZEY, GM</name>
        <lat>49.7281</lat>
        <lon>8.1167</lon>
    </station>
    <station>
        <id>GME00122602</id>
        <name>AMBERG UNTERAMMERSRICHT, GM</name>
        <lat>49.47</lat>
        <lon>11.8558</lon>
    </station>
    <station>
        <id>GME00122626</id>
        <name>FULDA, GM</name>
        <lat>50.5344</lat>
        <lon>9.6758</lon>
    </station>
    <station>
        <id>GME00122638</id>
        <name>GARDELEGEN, GM</name>
        <lat>52.5142</lat>
        <lon>11.3978</lon>
    </station>
    <station>
        <id>GME00122650</id>
        <name>AMERANG PFAFFING, GM</name>
        <lat>48.0206</lat>
        <lon>12.2939</lon>
    </station>
    <station>
        <id>GME00122698</id>
        <name>GEISENHEIM, GM</name>
        <lat>49.985</lat>
        <lon>7.9544</lon>
    </station>
    <station>
        <id>GME00122710</id>
        <name>GEISINGEN, GM</name>
        <lat>47.925</lat>
        <lon>8.6481</lon>
    </station>
    <station>
        <id>GME00122734</id>
        <name>GELBELSEE, GM</name>
        <lat>48.9489</lat>
        <lon>11.43</lon>
    </station>
    <station>
        <id>GME00122746</id>
        <name>GELDERN WALBECK, GM</name>
        <lat>51.4956</lat>
        <lon>6.2467</lon>
    </station>
    <station>
        <id>GME00122770</id>
        <name>OHLSBACH, GM</name>
        <lat>48.4339</lat>
        <lon>7.9933</lon>
    </station>
    <station>
        <id>GME00122782</id>
        <name>GENTHIN, GM</name>
        <lat>52.3892</lat>
        <lon>12.1633</lon>
    </station>
    <station>
        <id>GME00122794</id>
        <name>GERNRODE, GM</name>
        <lat>51.7269</lat>
        <lon>11.1331</lon>
    </station>
    <station>
        <id>GME00122806</id>
        <name>GERNSHEIM ALLMENDFELD, GM</name>
        <lat>49.7725</lat>
        <lon>8.5306</lon>
    </station>
    <station>
        <id>GME00122842</id>
        <name>GILSERBERG MOISCHEID, GM</name>
        <lat>50.9664</lat>
        <lon>9.0503</lon>
    </station>
    <station>
        <id>GME00122866</id>
        <name>GLUCKSTADT, GM</name>
        <lat>53.7983</lat>
        <lon>9.4306</lon>
    </station>
    <station>
        <id>GME00122878</id>
        <name>ANKLAM, GM</name>
        <lat>53.8431</lat>
        <lon>13.6856</lon>
    </station>
    <station>
        <id>GME00122890</id>
        <name>GOSSWEINSTEIN, GM</name>
        <lat>49.7667</lat>
        <lon>11.3075</lon>
    </station>
    <station>
        <id>GME00122902</id>
        <name>GOTTINGEN, GM</name>
        <lat>51.5017</lat>
        <lon>9.9528</lon>
    </station>
    <station>
        <id>GME00122938</id>
        <name>GRAFENBERG KASBERG, GM</name>
        <lat>49.665</lat>
        <lon>11.2253</lon>
    </station>
    <station>
        <id>GME00122962</id>
        <name>GRAINET REHBERG, GM</name>
        <lat>48.7903</lat>
        <lon>13.6306</lon>
    </station>
    <station>
        <id>GME00122974</id>
        <name>GRAMBEK, GM</name>
        <lat>53.5744</lat>
        <lon>10.6806</lon>
    </station>
    <station>
        <id>GME00122986</id>
        <name>GREBENHAIN HERCHENHAIN, GM</name>
        <lat>50.48</lat>
        <lon>9.2631</lon>
    </station>
    <station>
        <id>GME00123034</id>
        <name>GREIZ DOLAU, GM</name>
        <lat>50.6258</lat>
        <lon>12.1792</lon>
    </station>
    <station>
        <id>GME00123058</id>
        <name>GROSS LUSEWITZ, GM</name>
        <lat>54.0731</lat>
        <lon>12.3256</lon>
    </station>
    <station>
        <id>GME00123094</id>
        <name>FELDKIRCHEN WESTERHAM LENZMUHL, GM</name>
        <lat>47.9417</lat>
        <lon>11.9014</lon>
    </station>
    <station>
        <id>GME00123130</id>
        <name>GRUNDAU BREITENBORN, GM</name>
        <lat>50.2675</lat>
        <lon>9.1889</lon>
    </station>
    <station>
        <id>GME00123142</id>
        <name>GRUNOW, GM</name>
        <lat>53.3167</lat>
        <lon>13.9358</lon>
    </station>
    <station>
        <id>GME00123166</id>
        <name>KR. OSTALB GSCHWEND, GM</name>
        <lat>48.9364</lat>
        <lon>9.7375</lon>
    </station>
    <station>
        <id>GME00123178</id>
        <name>GUTERSLOH, GM</name>
        <lat>51.8889</lat>
        <lon>8.3553</lon>
    </station>
    <station>
        <id>GME00123190</id>
        <name>ARNSTEIN MUDESHEIM, GM</name>
        <lat>49.9706</lat>
        <lon>9.9125</lon>
    </station>
    <station>
        <id>GME00123202</id>
        <name>HAGEN FLEY, GM</name>
        <lat>51.4142</lat>
        <lon>7.4903</lon>
    </station>
    <station>
        <id>GME00123226</id>
        <name>OLSDORF, GM</name>
        <lat>49.9325</lat>
        <lon>6.3756</lon>
    </station>
    <station>
        <id>GME00123262</id>
        <name>HAMBURG KIRCHWERDER, GM</name>
        <lat>53.4228</lat>
        <lon>10.1475</lon>
    </station>
    <station>
        <id>GME00123274</id>
        <name>HAMBURG NEUWIEDENTHAL, GM</name>
        <lat>53.4792</lat>
        <lon>9.8983</lon>
    </station>
    <station>
        <id>GME00123310</id>
        <name>ARTERN, GM</name>
        <lat>51.3756</lat>
        <lon>11.2931</lon>
    </station>
    <station>
        <id>GME00123322</id>
        <name>HAMBURG WANDSBEK, GM</name>
        <lat>53.5867</lat>
        <lon>10.1306</lon>
    </station>
    <station>
        <id>GME00123334</id>
        <name>HAMELN, GM</name>
        <lat>52.085</lat>
        <lon>9.3892</lon>
    </station>
    <station>
        <id>GME00123370</id>
        <name>HANKENSBUTTEL, GM</name>
        <lat>52.7214</lat>
        <lon>10.6</lon>
    </station>
    <station>
        <id>GME00123382</id>
        <name>HARBURG, GM</name>
        <lat>48.7928</lat>
        <lon>10.7075</lon>
    </station>
    <station>
        <id>GME00123418</id>
        <name>HARZGERODE, GM</name>
        <lat>51.6531</lat>
        <lon>11.1375</lon>
    </station>
    <station>
        <id>GME00123466</id>
        <name>HECHINGEN, GM</name>
        <lat>48.3758</lat>
        <lon>8.9808</lon>
    </station>
    <station>
        <id>GME00123478</id>
        <name>WEDDINGSTEDT, GM</name>
        <lat>54.2194</lat>
        <lon>9.0864</lon>
    </station>
    <station>
        <id>GME00123538</id>
        <name>HEIDENHEIM BRENZ, GM</name>
        <lat>48.6731</lat>
        <lon>10.1331</lon>
    </station>
    <station>
        <id>GME00123562</id>
        <name>HEILBRONN, GM</name>
        <lat>49.1456</lat>
        <lon>9.2342</lon>
    </station>
    <station>
        <id>GME00123574</id>
        <name>HEINSBERG SCHLEIDEN, GM</name>
        <lat>51.0425</lat>
        <lon>6.1044</lon>
    </station>
    <station>
        <id>GME00123586</id>
        <name>ASSLAR KLEIN ALTENSTADTEN, GM</name>
        <lat>50.5808</lat>
        <lon>8.4692</lon>
    </station>
    <station>
        <id>GME00123598</id>
        <name>HELMSTEDT, GM</name>
        <lat>52.2178</lat>
        <lon>11.0231</lon>
    </station>
    <station>
        <id>GME00123610</id>
        <name>KR. DITHMARSCHEN HELSE, GM</name>
        <lat>53.9717</lat>
        <lon>9.0106</lon>
    </station>
    <station>
        <id>GME00123622</id>
        <name>HERFORD, GM</name>
        <lat>52.1278</lat>
        <lon>8.6875</lon>
    </station>
    <station>
        <id>GME00123646</id>
        <name>HERRENBERG, GM</name>
        <lat>48.5928</lat>
        <lon>8.8553</lon>
    </station>
    <station>
        <id>GME00123658</id>
        <name>HERRENHOF, GM</name>
        <lat>50.8456</lat>
        <lon>10.6917</lon>
    </station>
    <station>
        <id>GME00123682</id>
        <name>NIEDERWORRESBACH, GM</name>
        <lat>49.7681</lat>
        <lon>7.3364</lon>
    </station>
    <station>
        <id>GME00123694</id>
        <name>BAD HERSFELD, GM</name>
        <lat>50.8531</lat>
        <lon>9.7383</lon>
    </station>
    <station>
        <id>GME00123706</id>
        <name>HERTEN, GM</name>
        <lat>51.5903</lat>
        <lon>7.1556</lon>
    </station>
    <station>
        <id>GME00123718</id>
        <name>HERZBERG, GM</name>
        <lat>51.6267</lat>
        <lon>10.3717</lon>
    </station>
    <station>
        <id>GME00123730</id>
        <name>ATTENKAM, GM</name>
        <lat>47.8781</lat>
        <lon>11.3656</lon>
    </station>
    <station>
        <id>GME00123766</id>
        <name>HILDESHEIM, GM</name>
        <lat>52.1419</lat>
        <lon>9.885</lon>
    </station>
    <station>
        <id>GME00123778</id>
        <name>HILGENROTH, GM</name>
        <lat>50.7381</lat>
        <lon>7.6533</lon>
    </station>
    <station>
        <id>GME00123802</id>
        <name>HINDFELD, GM</name>
        <lat>50.3683</lat>
        <lon>10.57</lon>
    </station>
    <station>
        <id>GME00123814</id>
        <name>EISFELD WAFFENROD HINTERROD, GM</name>
        <lat>50.4717</lat>
        <lon>10.9117</lon>
    </station>
    <station>
        <id>GME00123838</id>
        <name>AUE, GM</name>
        <lat>50.5917</lat>
        <lon>12.7156</lon>
    </station>
    <station>
        <id>GME00123850</id>
        <name>HOLLENSTEIN KRAFTWERK, GM</name>
        <lat>49.1289</lat>
        <lon>12.8658</lon>
    </station>
    <station>
        <id>GME00123862</id>
        <name>BERTSDORF HORNITZ, GM</name>
        <lat>50.9006</lat>
        <lon>14.7475</lon>
    </station>
    <station>
        <id>GME00123874</id>
        <name>HOF STADT, GM</name>
        <lat>50.3242</lat>
        <lon>11.9092</lon>
    </station>
    <station>