<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="../details.xsl"?>
<!DOCTYPE root [
        <!ELEMENT root (id|name|lat|lon|ele|year)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT lat (#PCDATA)>
        <!ELEMENT lon (#PCDATA)>
        <!ELEMENT ele (#PCDATA)>
        <!ELEMENT year (date|EMNT|EMXT|TMAX|TMIN|TAVG)*>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT EMNT (#PCDATA)>
        <!ELEMENT EMXT (#PCDATA)>
        <!ELEMENT TMAX (#PCDATA)>
        <!ELEMENT TMIN (#PCDATA)>
        <!ELEMENT TAVG (#PCDATA)>
        ]>
<root>
    <id>GME00127222</id>
    <name>PELZERHAKEN, GM</name>
    <lat>54.0906</lat>
    <lon>10.8783</lon>
    <ele>1.0</ele>
    <year>
        <date>1999</date>
        <EMNT>undefined</EMNT>
        <EMXT>undefined</EMXT>
        <TMAX>undefined</TMAX>
        <TMIN>undefined</TMIN>
        <TAVG>undefined</TAVG>
    </year>
    <year>
        <date>2002</date>
        <EMNT>-8.6</EMNT>
        <EMXT>30.4</EMXT>
        <TMAX>12.6</TMAX>
        <TMIN>6.6</TMIN>
        <TAVG>9.6</TAVG>
    </year>
    <year>
        <date>2003</date>
        <EMNT>undefined</EMNT>
        <EMXT>undefined</EMXT>
        <TMAX>undefined</TMAX>
        <TMIN>undefined</TMIN>
        <TAVG>undefined</TAVG>
    </year>
    <year>
        <date>2007</date>
        <EMNT>-7.3</EMNT>
        <EMXT>30.0</EMXT>
        <TMAX>13.4</TMAX>
        <TMIN>6.8</TMIN>
        <TAVG>10.1</TAVG>
    </year>
    <year>
        <date>2008</date>
        <EMNT>-7.4</EMNT>
        <EMXT>27.5</EMXT>
        <TMAX>13.2</TMAX>
        <TMIN>6.6</TMIN>
        <TAVG>9.9</TAVG>
    </year>
    <year>
        <date>2009</date>
        <EMNT>-14.2</EMNT>
        <EMXT>30.2</EMXT>
        <TMAX>12.8</TMAX>
        <TMIN>5.8</TMIN>
        <TAVG>9.3</TAVG>
    </year>
    <year>
        <date>2010</date>
        <EMNT>-15.0</EMNT>
        <EMXT>31.0</EMXT>
        <TMAX>11.3</TMAX>
        <TMIN>4.4</TMIN>
        <TAVG>7.9</TAVG>
    </year>
    <year>
        <date>2011</date>
        <EMNT>-8.0</EMNT>
        <EMXT>27.6</EMXT>
        <TMAX>12.8</TMAX>
        <TMIN>6.1</TMIN>
        <TAVG>9.4</TAVG>
    </year>
    <year>
        <date>2012</date>
        <EMNT>-16.9</EMNT>
        <EMXT>30.4</EMXT>
        <TMAX>12.4</TMAX>
        <TMIN>5.4</TMIN>
        <TAVG>8.9</TAVG>
    </year>
    <year>
        <date>2013</date>
        <EMNT>-11.8</EMNT>
        <EMXT>29.6</EMXT>
        <TMAX>12.3</TMAX>
        <TMIN>5.5</TMIN>
        <TAVG>8.9</TAVG>
    </year>
    <year>
        <date>2014</date>
        <EMNT>-11.4</EMNT>
        <EMXT>27.4</EMXT>
        <TMAX>13.7</TMAX>
        <TMIN>7.1</TMIN>
        <TAVG>10.4</TAVG>
    </year>
    <year>
        <date>2015</date>
        <EMNT>-7.1</EMNT>
        <EMXT>29.9</EMXT>
        <TMAX>13.3</TMAX>
        <TMIN>6.3</TMIN>
        <TAVG>9.8</TAVG>
    </year>
    <year>
        <date>2016</date>
        <EMNT>-7.7</EMNT>
        <EMXT>32.6</EMXT>
        <TMAX>13.1</TMAX>
        <TMIN>6.3</TMIN>
        <TAVG>9.7</TAVG>
    </year>
    <year>
        <date>2017</date>
        <EMNT>-12.5</EMNT>
        <EMXT>26.6</EMXT>
        <TMAX>12.9</TMAX>
        <TMIN>6.3</TMIN>
        <TAVG>9.6</TAVG>
    </year>
    <year>
        <date>2018</date>
        <EMNT>-10.6</EMNT>
        <EMXT>34.2</EMXT>
        <TMAX>13.7</TMAX>
        <TMIN>6.3</TMIN>
        <TAVG>10.0</TAVG>
    </year>
    <year>
        <date>2019</date>
        <EMNT>-5.7</EMNT>
        <EMXT>33.3</EMXT>
        <TMAX>13.8</TMAX>
        <TMIN>6.6</TMIN>
        <TAVG>10.2</TAVG>
    </year>
    <year>
        <date>2020</date>
        <EMNT>-4.5</EMNT>
        <EMXT>29.3</EMXT>
        <TMAX>14.1</TMAX>
        <TMIN>6.8</TMIN>
        <TAVG>10.4</TAVG>
    </year>
</root>