<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="../details.xsl"?>
<!DOCTYPE root [
        <!ELEMENT root (id|name|lat|lon|ele|year)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT lat (#PCDATA)>
        <!ELEMENT lon (#PCDATA)>
        <!ELEMENT ele (#PCDATA)>
        <!ELEMENT year (date|EMNT|EMXT|TMAX|TMIN|TAVG)*>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT EMNT (#PCDATA)>
        <!ELEMENT EMXT (#PCDATA)>
        <!ELEMENT TMAX (#PCDATA)>
        <!ELEMENT TMIN (#PCDATA)>
        <!ELEMENT TAVG (#PCDATA)>
        ]>
<root>
    <id>GME00122446</id>
    <name>FREIBERG, GM</name>
    <lat>50.9281</lat>
    <lon>13.3389</lon>
    <ele>380.0</ele>
    <year>
        <date>1970</date>
        <EMNT>-17.1</EMNT>
        <EMXT>30.3</EMXT>
        <TMAX>11.1</TMAX>
        <TMIN>3.9</TMIN>
        <TAVG>7.4</TAVG>
    </year>
    <year>
        <date>1971</date>
        <EMNT>-18.4</EMNT>
        <EMXT>32.0</EMXT>
        <TMAX>12.3</TMAX>
        <TMIN>4.5</TMIN>
        <TAVG>8.4</TAVG>
    </year>
    <year>
        <date>1972</date>
        <EMNT>-14.5</EMNT>
        <EMXT>33.0</EMXT>
        <TMAX>11.9</TMAX>
        <TMIN>4.4</TMIN>
        <TAVG>8.1</TAVG>
    </year>
    <year>
        <date>1973</date>
        <EMNT>-12.7</EMNT>
        <EMXT>31.1</EMXT>
        <TMAX>11.9</TMAX>
        <TMIN>4.3</TMIN>
        <TAVG>8.1</TAVG>
    </year>
    <year>
        <date>1974</date>
        <EMNT>-7.0</EMNT>
        <EMXT>32.7</EMXT>
        <TMAX>12.4</TMAX>
        <TMIN>5.3</TMIN>
        <TAVG>8.8</TAVG>
    </year>
    <year>
        <date>1975</date>
        <EMNT>-12.8</EMNT>
        <EMXT>31.2</EMXT>
        <TMAX>12.8</TMAX>
        <TMIN>5.0</TMIN>
        <TAVG>8.9</TAVG>
    </year>
    <year>
        <date>1976</date>
        <EMNT>-17.5</EMNT>
        <EMXT>34.2</EMXT>
        <TMAX>12.3</TMAX>
        <TMIN>4.0</TMIN>
        <TAVG>8.2</TAVG>
    </year>
    <year>
        <date>1977</date>
        <EMNT>-13.0</EMNT>
        <EMXT>28.7</EMXT>
        <TMAX>12.4</TMAX>
        <TMIN>5.2</TMIN>
        <TAVG>8.8</TAVG>
    </year>
    <year>
        <date>1978</date>
        <EMNT>-19.1</EMNT>
        <EMXT>29.6</EMXT>
        <TMAX>11.6</TMAX>
        <TMIN>4.1</TMIN>
        <TAVG>7.9</TAVG>
    </year>
    <year>
        <date>1979</date>
        <EMNT>-21.0</EMNT>
        <EMXT>30.6</EMXT>
        <TMAX>11.8</TMAX>
        <TMIN>4.2</TMIN>
        <TAVG>8.0</TAVG>
    </year>
    <year>
        <date>1980</date>
        <EMNT>-19.8</EMNT>
        <EMXT>31.0</EMXT>
        <TMAX>11.0</TMAX>
        <TMIN>3.5</TMIN>
        <TAVG>7.3</TAVG>
    </year>
    <year>
        <date>1981</date>
        <EMNT>-19.1</EMNT>
        <EMXT>30.4</EMXT>
        <TMAX>12.0</TMAX>
        <TMIN>4.2</TMIN>
        <TAVG>8.1</TAVG>
    </year>
    <year>
        <date>1982</date>
        <EMNT>-19.5</EMNT>
        <EMXT>30.6</EMXT>
        <TMAX>13.5</TMAX>
        <TMIN>5.0</TMIN>
        <TAVG>9.2</TAVG>
    </year>
    <year>
        <date>1983</date>
        <EMNT>-17.1</EMNT>
        <EMXT>34.2</EMXT>
        <TMAX>13.1</TMAX>
        <TMIN>5.2</TMIN>
        <TAVG>9.2</TAVG>
    </year>
    <year>
        <date>1984</date>
        <EMNT>-15.5</EMNT>
        <EMXT>34.3</EMXT>
        <TMAX>11.4</TMAX>
        <TMIN>4.2</TMIN>
        <TAVG>7.8</TAVG>
    </year>
    <year>
        <date>1985</date>
        <EMNT>-22.6</EMNT>
        <EMXT>31.6</EMXT>
        <TMAX>11.4</TMAX>
        <TMIN>3.6</TMIN>
        <TAVG>7.5</TAVG>
    </year>
    <year>
        <date>1986</date>
        <EMNT>-21.6</EMNT>
        <EMXT>32.0</EMXT>
        <TMAX>11.9</TMAX>
        <TMIN>4.1</TMIN>
        <TAVG>8.0</TAVG>
    </year>
    <year>
        <date>1987</date>
        <EMNT>-23.7</EMNT>
        <EMXT>30.3</EMXT>
        <TMAX>10.8</TMAX>
        <TMIN>3.4</TMIN>
        <TAVG>7.1</TAVG>
    </year>
    <year>
        <date>1988</date>
        <EMNT>-11.1</EMNT>
        <EMXT>31.2</EMXT>
        <TMAX>12.5</TMAX>
        <TMIN>5.1</TMIN>
        <TAVG>8.8</TAVG>
    </year>
    <year>
        <date>1989</date>
        <EMNT>-10.6</EMNT>
        <EMXT>31.6</EMXT>
        <TMAX>14.0</TMAX>
        <TMIN>5.6</TMIN>
        <TAVG>9.8</TAVG>
    </year>
    <year>
        <date>1990</date>
        <EMNT>-10.1</EMNT>
        <EMXT>32.3</EMXT>
        <TMAX>13.6</TMAX>
        <TMIN>5.9</TMIN>
        <TAVG>9.7</TAVG>
    </year>
    <year>
        <date>1991</date>
        <EMNT>-20.7</EMNT>
        <EMXT>33.3</EMXT>
        <TMAX>12.3</TMAX>
        <TMIN>4.2</TMIN>
        <TAVG>8.3</TAVG>
    </year>
    <year>
        <date>1992</date>
        <EMNT>-12.0</EMNT>
        <EMXT>34.3</EMXT>
        <TMAX>13.4</TMAX>
        <TMIN>5.1</TMIN>
        <TAVG>9.3</TAVG>
    </year>
    <year>
        <date>2016</date>
        <EMNT>undefined</EMNT>
        <EMXT>undefined</EMXT>
        <TMAX>undefined</TMAX>
        <TMIN>undefined</TMIN>
        <TAVG>undefined</TAVG>
    </year>
    <year>
        <date>2017</date>
        <EMNT>undefined</EMNT>
        <EMXT>undefined</EMXT>
        <TMAX>undefined</TMAX>
        <TMIN>undefined</TMIN>
        <TAVG>undefined</TAVG>
    </year>
    <year>
        <date>2018</date>
        <EMNT>undefined</EMNT>
        <EMXT>undefined</EMXT>
        <TMAX>undefined</TMAX>
        <TMIN>undefined</TMIN>
        <TAVG>undefined</TAVG>
    </year>
    <year>
        <date>2019</date>
        <EMNT>undefined</EMNT>
        <EMXT>undefined</EMXT>
        <TMAX>undefined</TMAX>
        <TMIN>undefined</TMIN>
        <TAVG>undefined</TAVG>
    </year>
    <year>
        <date>2020</date>
        <EMNT>undefined</EMNT>
        <EMXT>undefined</EMXT>
        <TMAX>undefined</TMAX>
        <TMIN>undefined</TMIN>
        <TAVG>undefined</TAVG>
    </year>
</root>