<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="../../xml/details.xsl"?>
<!DOCTYPE root [
        <!ELEMENT root (id|name|lat|lon|ele|year)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT lat (#PCDATA)>
        <!ELEMENT lon (#PCDATA)>
        <!ELEMENT ele (#PCDATA)>
        <!ELEMENT year (date|EMNT|EMXT|TMAX|TMIN|TAVG)*>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT EMNT (#PCDATA)>
        <!ELEMENT EMXT (#PCDATA)>
        <!ELEMENT TMAX (#PCDATA)>
        <!ELEMENT TMIN (#PCDATA)>
        <!ELEMENT TAVG (#PCDATA)>
        ]>
<root>
    <id>GME00132070</id>
    <name>FEUCHTWANGEN HEILBRONN, GM</name>
    <lat>49.1631</lat>
    <lon>10.3669</lon>
    <ele>475.0</ele>
    <year>
        <date>2008</date>
        <EMNT>-9.2</EMNT>
        <EMXT>30.7</EMXT>
        <TMAX>13.2</TMAX>
        <TMIN>4.2</TMIN>
        <TAVG>8.7</TAVG>
    </year>
    <year>
        <date>2009</date>
        <EMNT>-18.7</EMNT>
        <EMXT>31.9</EMXT>
        <TMAX>12.9</TMAX>
        <TMIN>3.6</TMIN>
        <TAVG>8.2</TAVG>
    </year>
    <year>
        <date>2010</date>
        <EMNT>-17.4</EMNT>
        <EMXT>33.9</EMXT>
        <TMAX>11.5</TMAX>
        <TMIN>2.8</TMIN>
        <TAVG>7.1</TAVG>
    </year>
    <year>
        <date>2011</date>
        <EMNT>-12.8</EMNT>
        <EMXT>33.2</EMXT>
        <TMAX>13.9</TMAX>
        <TMIN>3.9</TMIN>
        <TAVG>8.9</TAVG>
    </year>
    <year>
        <date>2012</date>
        <EMNT>-19.4</EMNT>
        <EMXT>34.0</EMXT>
        <TMAX>13.3</TMAX>
        <TMIN>3.5</TMIN>
        <TAVG>8.4</TAVG>
    </year>
    <year>
        <date>2013</date>
        <EMNT>-11.4</EMNT>
        <EMXT>34.8</EMXT>
        <TMAX>12.2</TMAX>
        <TMIN>4.0</TMIN>
        <TAVG>8.1</TAVG>
    </year>
    <year>
        <date>2014</date>
        <EMNT>-14.4</EMNT>
        <EMXT>33.4</EMXT>
        <TMAX>14.3</TMAX>
        <TMIN>5.1</TMIN>
        <TAVG>9.7</TAVG>
    </year>
    <year>
        <date>2015</date>
        <EMNT>-14.7</EMNT>
        <EMXT>36.5</EMXT>
        <TMAX>14.4</TMAX>
        <TMIN>4.5</TMIN>
        <TAVG>9.4</TAVG>
    </year>
    <year>
        <date>2016</date>
        <EMNT>-15.6</EMNT>
        <EMXT>33.1</EMXT>
        <TMAX>13.5</TMAX>
        <TMIN>4.3</TMIN>
        <TAVG>8.9</TAVG>
    </year>
    <year>
        <date>2017</date>
        <EMNT>-19.1</EMNT>
        <EMXT>32.5</EMXT>
        <TMAX>13.6</TMAX>
        <TMIN>4.1</TMIN>
        <TAVG>8.8</TAVG>
    </year>
    <year>
        <date>2018</date>
        <EMNT>-15.3</EMNT>
        <EMXT>34.1</EMXT>
        <TMAX>15.0</TMAX>
        <TMIN>4.6</TMIN>
        <TAVG>9.8</TAVG>
    </year>
    <year>
        <date>2019</date>
        <EMNT>-9.6</EMNT>
        <EMXT>36.1</EMXT>
        <TMAX>14.5</TMAX>
        <TMIN>4.2</TMIN>
        <TAVG>9.4</TAVG>
    </year>
    <year>
        <date>2020</date>
        <EMNT>-8.2</EMNT>
        <EMXT>33.5</EMXT>
        <TMAX>14.5</TMAX>
        <TMIN>4.2</TMIN>
        <TAVG>9.4</TAVG>
    </year>
</root>