<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="../details.xsl"?>
<!DOCTYPE root [
        <!ELEMENT root (id|name|lat|lon|ele|year)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT lat (#PCDATA)>
        <!ELEMENT lon (#PCDATA)>
        <!ELEMENT ele (#PCDATA)>
        <!ELEMENT year (date|EMNT|EMXT|TMAX|TMIN|TAVG)*>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT EMNT (#PCDATA)>
        <!ELEMENT EMXT (#PCDATA)>
        <!ELEMENT TMAX (#PCDATA)>
        <!ELEMENT TMIN (#PCDATA)>
        <!ELEMENT TAVG (#PCDATA)>
        ]>
<root>
    <id>GME00131422</id>
    <name>DEMKER, GM</name>
    <lat>52.5083</lat>
    <lon>11.8564</lon>
    <ele>36.0</ele>
    <year>
        <date>2005</date>
        <EMNT>-10.7</EMNT>
        <EMXT>33.3</EMXT>
        <TMAX>14.3</TMAX>
        <TMIN>4.7</TMIN>
        <TAVG>9.5</TAVG>
    </year>
    <year>
        <date>2006</date>
        <EMNT>-15.6</EMNT>
        <EMXT>37.5</EMXT>
        <TMAX>14.9</TMAX>
        <TMIN>5.3</TMIN>
        <TAVG>10.1</TAVG>
    </year>
    <year>
        <date>2007</date>
        <EMNT>-7.8</EMNT>
        <EMXT>36.8</EMXT>
        <TMAX>15.1</TMAX>
        <TMIN>6.1</TMIN>
        <TAVG>10.6</TAVG>
    </year>
    <year>
        <date>2008</date>
        <EMNT>-10.1</EMNT>
        <EMXT>34.0</EMXT>
        <TMAX>14.8</TMAX>
        <TMIN>5.6</TMIN>
        <TAVG>10.2</TAVG>
    </year>
    <year>
        <date>2009</date>
        <EMNT>-17.4</EMNT>
        <EMXT>34.9</EMXT>
        <TMAX>14.5</TMAX>
        <TMIN>4.8</TMIN>
        <TAVG>9.6</TAVG>
    </year>
    <year>
        <date>2010</date>
        <EMNT>-18.7</EMNT>
        <EMXT>37.5</EMXT>
        <TMAX>12.7</TMAX>
        <TMIN>3.7</TMIN>
        <TAVG>8.2</TAVG>
    </year>
    <year>
        <date>2011</date>
        <EMNT>-12.4</EMNT>
        <EMXT>33.3</EMXT>
        <TMAX>15.1</TMAX>
        <TMIN>5.2</TMIN>
        <TAVG>10.2</TAVG>
    </year>
    <year>
        <date>2012</date>
        <EMNT>-20.5</EMNT>
        <EMXT>36.3</EMXT>
        <TMAX>14.3</TMAX>
        <TMIN>4.7</TMIN>
        <TAVG>9.5</TAVG>
    </year>
    <year>
        <date>2013</date>
        <EMNT>-15.2</EMNT>
        <EMXT>36.8</EMXT>
        <TMAX>13.8</TMAX>
        <TMIN>5.0</TMIN>
        <TAVG>9.4</TAVG>
    </year>
    <year>
        <date>2014</date>
        <EMNT>-13.5</EMNT>
        <EMXT>34.3</EMXT>
        <TMAX>15.6</TMAX>
        <TMIN>6.1</TMIN>
        <TAVG>10.9</TAVG>
    </year>
    <year>
        <date>2015</date>
        <EMNT>-8.6</EMNT>
        <EMXT>38.4</EMXT>
        <TMAX>15.2</TMAX>
        <TMIN>5.5</TMIN>
        <TAVG>10.4</TAVG>
    </year>
    <year>
        <date>2016</date>
        <EMNT>-15.3</EMNT>
        <EMXT>36.0</EMXT>
        <TMAX>15.0</TMAX>
        <TMIN>5.4</TMIN>
        <TAVG>10.2</TAVG>
    </year>
    <year>
        <date>2017</date>
        <EMNT>-11.9</EMNT>
        <EMXT>31.6</EMXT>
        <TMAX>14.7</TMAX>
        <TMIN>5.7</TMIN>
        <TAVG>10.2</TAVG>
    </year>
    <year>
        <date>2018</date>
        <EMNT>-13.1</EMNT>
        <EMXT>38.7</EMXT>
        <TMAX>16.4</TMAX>
        <TMIN>5.6</TMIN>
        <TAVG>11.0</TAVG>
    </year>
    <year>
        <date>2019</date>
        <EMNT>-7.6</EMNT>
        <EMXT>38.2</EMXT>
        <TMAX>16.3</TMAX>
        <TMIN>5.9</TMIN>
        <TAVG>11.1</TAVG>
    </year>
    <year>
        <date>2020</date>
        <EMNT>-6.1</EMNT>
        <EMXT>36.3</EMXT>
        <TMAX>16.2</TMAX>
        <TMIN>5.9</TMIN>
        <TAVG>11.1</TAVG>
    </year>
</root>